---
- name: Define variaveis para o ambiente de producao
  set_fact: ldap_groups={{ ldap_groups_prod }}
            ldap_username={{ ldap_username_prod }}
            ldap_password={{ ldap_password_prod }}
            wls_password={{ wls_password_prod }}
            ipa_acl_usergroup={{ ipa_acl_usergroup_prd }}
  no_log: false
  when: ambiente == "PROD"

- name: Define variaveis para o ambiente de homologacao
  set_fact: ldap_groups={{ ldap_groups_hom }}
            ldap_username={{ ldap_username_hom }}
            ldap_password={{ ldap_password_hom }}
            wls_password={{ wls_password_hom }}
            ipa_acl_usergroup={{ ipa_acl_usergroup_hom }}
  no_log: false
  when: ambiente == "HOM"

- name: Define variaveis para o ambiente de desenvolvimento
  set_fact: ldap_groups={{ ldap_groups_dev }}
            ldap_username={{ ldap_username_dev }}
            ldap_password={{ ldap_password_dev }}
            wls_password={{ wls_password_dev }}
            ipa_acl_usergroup={{ ipa_acl_usergroup_dev }}
  no_log: false
  when: ambiente == "DEV"

- name: Define variaveis para a versao 12.1.3
  set_fact: wls_patchs="files/patchs_12130/*"
  no_log: false
  when: wls_version == "12.1.3.0"

- name: Define variaveis para a versao 12.2.1.3
  set_fact: wls_patchs="files/patchs_12212/*"
  no_log: false
  when: wls_version == "12.2.1.3"
